name: mx_app_icon
description: App icon generator.
version: 1.0.1
repository: https://github.com/MagicalWater/mx_app_icon

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  image: ^4.1.3
  args: ^2.4.2
  decimal: ^2.3.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  mx_app_icon:
