name: mx_app_icon
description: App icon generator.
version: 1.1.0
repository: https://github.com/MagicalWater/mx_app_icon

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  image: ^4.2.0
  args: ^2.5.0
  decimal: ^3.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

executables:
  mx_app_icon:
